//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Tracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductStore
    {
        public int ProductStoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Store tbl_Store { get; set; }
    }
}
