//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Tracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_ProductStore = new HashSet<tbl_ProductStore>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> ProductPackingDate { get; set; }
        public Nullable<System.DateTime> ProductExpireDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DealsId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tbl_Deals tbl_Deals { get; set; }
        public virtual tbl_Product tbl_Product1 { get; set; }
        public virtual tbl_Product tbl_Product2 { get; set; }
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
        public virtual tbl_ProductStatus tbl_ProductStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductStore> tbl_ProductStore { get; set; }
    }
}
